development:
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_ID"] %>

# production:
#   access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
#   secret_access_key: <%= ENV["SECRET_ACCESS_KEY_ID"] %>

production:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_ID"] %>